### ISSUE TITLE
unintended keystrokes recorded with xev on Ubuntu 17.10

### ISSUE THREAD

**Issue by RWBYKing** [RaulPPelaez/Naga_KeypadMapper#57] opened 2018-05-07 06:31 UTC
Please keep in mind that I don't have a lot of knowledge about the inner workings of Ubuntu, but I can follow instructions, if given.

Some relevant terminal outputs:

```
$ sudo naga
Starting naga daemon
Reading from: /dev/input/by-id/usb-Razer_Razer_Naga_Chroma-if02-event-kbd and /dev/input/by-id/usb-Razer_Razer_Naga_Chroma-event-mouse
Line : KP_1
Line : KP_2
Line : KP_3
Line : KP_4
Line : KP_5
Line : KP_6
Line : KP_7
Line : KP_8
Line : KP_9
Line : F1
Line : F2
Line : F3
^C

relevant xev output:
KeyPress event, serial 37, synthetic NO, window 0x4600001,
    root 0x1ef, subw 0x0, time 63942455, (1358,423), root:(3066,481),
    state 0x10, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 38, synthetic NO, window 0x4600001,
    root 0x1ef, subw 0x0, time 63942463, (1358,423), root:(3066,481),
    state 0x11, keycode 87 (keysym 0xff9c, KP_End), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 38, synthetic NO, window 0x4600001,
    root 0x1ef, subw 0x0, time 63942568, (1358,423), root:(3066,481),
    state 0x11, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 38, synthetic NO, window 0x4600001,
    root 0x1ef, subw 0x0, time 63942568, (1358,423), root:(3066,481),
    state 0x10, keycode 87 (keysym 0xffb1, KP_1), same_screen YES,
    XLookupString gives 1 bytes: (31) "1"
    XFilterEvent returns: False
```

**Comment by RaulPPelaez** [comment] 2018-08-06 10:16
Sorry for the late reply. And sorry again because I really do not understand what the issue is here.. What is your mapping.txt? Maybe this is happening inside a macro?.
I am closing this issue now, but if you still have issues please feel free to reopen it.

**Closed by RaulPPelaez** 2018-08-06 10:16 UTC
